# Generated by Django 2.1.1 on 2018-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayments',
            name='is_safe',
            field=models.BooleanField(default=True, verbose_name='Безопасный'),
        ),
    ]
